Mvc5_Project/Controllers/SellersController.cs
using Mvc5_Project.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using X.PagedList;

namespace Mvc5_Project.Controllers
{
    [Authorize(Roles = "Admin, Customers")]

    public class SellersController : Controller
    {

        private readonly ProductDbContext db = new ProductDbContext();
        // GET: Sellers
        public ActionResult Index()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Seller model)
        {
            if (ModelState.IsValid)
            {
                db.Sellers.Add(model);
                db.SaveChanges();
                return PartialView("_Success");
            }
            return PartialView("_Fail");
        }

        [Authorize(Roles = "Admin")]

        public ActionResult Edit(int id)
        {
            var data = db.Sellers.FirstOrDefault(x => x.SellerId == id);
            if (data == null) return new HttpNotFoundResult();
            return View(data);
        }
        [HttpPost]
        public ActionResult Edit(Seller model)
        {
            if (ModelState.IsValid)
            {
                db.Entry(model).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return PartialView("_Success");
            }
            return PartialView("_Fail");
        }
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            var seller = db.Sellers.FirstOrDefault(x => x.SellerId == id);
            if (seller == null) return new HttpNotFoundResult();
            db.Sellers.Remove(seller);
            db.SaveChanges();
            return Json(new { success = true });
        }
        public PartialViewResult SellersTable(int pg = 1)
        {
            var data = db.Sellers.OrderBy(x => x.SellerId).ToPagedList(pg, 5);
            return PartialView("_Sellers", data);
        }
    }
}

Mvc5_Project/Views/Sellers/Create.cshtml
@model Mvc5_Project.Models.Seller
@{
    ViewBag.Title = "Create";
}

<div class="row">
    <div class="col-12">
        <div id="msg">

        </div>
        @using (Ajax.BeginForm("Create", "Sellers", new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "msg", OnSuccess = "onSuccess" }, new { id = "frm" }))
        {
            <h3>Add New Seller</h3>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.SallerName, new { @class = "col-form-label col-2 text-end" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.SallerName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.SallerName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.SellerAddress, new { @class = "col-form-label col-2 text-end" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.SellerAddress, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.SellerAddress, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">

                <div class="col-4">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </div>
        }
    </div>
    <div class="col-12">
        @Html.ActionLink("Return to Seller list", "Index")
    </div>
</div>

@section scripts
{
    <script src="~/Scripts/jquery-3.7.1.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script>
        function onSuccess() {
            $("#frm").trigger("reset");
        }
    </script>
}

Mvc5_Project/Views/Sellers/Edit.cshtml
@model Mvc5_Project.Models.Seller
@{
    ViewBag.Title = "Edit";
}

<div class="row">
    <div class="col-12">
        <div id="msg">

        </div>
        @using (Ajax.BeginForm("Edit", "Sellers", new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "msg" }, new { id = "frm" }))
        {
            @Html.HiddenFor(x => x.SellerId)
            <h3>Edit Seller</h3>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.SallerName, new { @class = "col-form-label col-2 text-end" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.SallerName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.SallerName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.SellerAddress, new { @class = "col-form-label col-2 text-end" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.SellerAddress, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.SellerAddress, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">

                <div class="col-4">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </div>
        }
    </div>
    <div class="col-12">
        @Html.ActionLink("Return to Seller list", "Index")
    </div>
</div>

@section scripts
{
    <script src="~/Scripts/jquery-3.7.1.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    
}

Mvc5_Project/Views/Sellers/Index.cshtml
@model IEnumerable<Mvc5_Project.Models.Seller>

@{
    ViewBag.Title = "Index";
}
<div class="row">
    <div class="col-12" id="placeholder">

        @Html.Action("SellersTable", "Sellers")
    </div>
</div>

@section scripts
{
    <script src="~/Scripts/jquery-3.7.1.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script>
        $(".del").click(function () {
            var id = $(this).data("pk");
            var trC = $(this).closest('tr');

            if (confirm("Are you sure to delete Seller?")) {
                $.ajax({
                    url: "/Sellers/Delete/" + id,
                    method: "post",
                    dataType: "json",
                    success: r => {
                        if (r.success == true) {
                            trC.remove();

                        }
                    }
                })
            }
        });
    </script>
}

Mvc5_Project/Views/Sellers/_Sellers.cshtml
@model IEnumerable<Mvc5_Project.Models.Seller>
@using X.PagedList
@using X.PagedList.Mvc
@using X.PagedList.Mvc.Common

<h2>Sellers</h2>
<div class="d-flex justify-content-end mb-1">
    @Html.ActionLink("Create New", "Create", "Sellers", new { }, new { @class = "btn btn-primary btn-sm" })
</div>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Saller Name</th>
            <th>SellerAddress</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var m in Model)
        {
            <tr>
                <td>@m.SallerName</td>
                <td>@m.SellerAddress</td>
                <td>
                    @Html.ActionLink("Edit", "Edit", "Sellers", new { id = m.SellerId }, new { @class = "btn btn-primary btn-sm" })
                    <button type="button" data-pk="@m.SellerId" class="btn btn-danger btn-sm del">Delete</button>
                </td>
                
            </tr>
        }
    </tbody>
</table>
<div class="d-flex justify-content-end">

    @Html.PagedListPager((IPagedList)Model, pg => Url.Action("SellersTable", "Sellers", new { pg = pg }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new PagedListRenderOptions
    {
        UlElementClasses = new string[] { "pagination", "pagination-sm" },
        LiElementClasses = new string[] { "page-item" },
        PageClasses = new string[] { "page-link" },
        DisplayLinkToPreviousPage = PagedListDisplayMode.Always,
        DisplayLinkToNextPage = PagedListDisplayMode.Always
    },
    new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "placeholder" }))
</div>