Mvc5_Project/Controllers/GroupingsController.cs
using Mvc5_Project.Models;
using Mvc5_Project.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace Mvc5_Project.Controllers
{
    public class GroupingsController : Controller
    {
        private readonly ProductDbContext db = new ProductDbContext();
        // GET: Groupings
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult GroupingByProductName()
        {
            var data = db.Sales.Include(x => x.Product).ToList()
                .GroupBy(s => s.Product.ProductName)
                .Select(g => new GroupedData { Key = g.Key, Data = g.Select(x => x) })
                .ToList();

            return View(data);
        }
        public ActionResult GroupingBySaleDate()
        {
            var data = db.Sales
                .ToList()
               .GroupBy(s => s.SaleDate)
               .Select(g => new GroupedData { Key = g.Key.ToString("yyyy-MM-dd"), Data = g.Select(x => x) })
               .ToList();
            return View(data);
        }
    }
}

Mvc5_Project/Views/Shared/_Fail.cshtml
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>Failed!</strong> Failed to Add New Seller.
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

Mvc5_Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.bundle.js"></script>
    <style>
        body {
            padding-top: 70px;
        }

        .main {
            min-height: calc(100vh - 110px);
        }
    </style>
    @RenderSection("styles", false)
</head>
<body>


    <navbar class="navbar bg-info navbar-expand-md fixed-top shadow-sm px-2">
        <div class="container-fluid">
            <span class="navbar-brand">Product Managment</span>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#nv" aria-controls="nv" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse" id="nv">
                <ul class="navbar-nav ">
                    <li class="nav-item">
                        @Html.ActionLink("Home", "Index", "Home", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Sellers", "Index", "Sellers", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Products", "Index", "Products", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Aggregates", "Index", "Aggregates", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("GroupingByProductName", "GroupingByProductName", "Groupings", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("GroupingBySaleDate", "GroupingBySaleDate", "Groupings", new { }, new { @class = "nav-link" })
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto">
                    @if (Request.IsAuthenticated)
                    {
                        <li class="nav-item">
                            @Html.ActionLink("Logout", "Logout", "Account", new { }, new { @class = "nav-link" })
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            @Html.ActionLink("Register", "Register", "Account", new { }, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Login", "Login", "Account", new { }, new { @class = "nav-link" })
                        </li>
                    }
                </ul>
            </div>

        </div>
    </navbar>
    <main class="container-fluid main">
        @RenderBody()
    </main>
    <footer class="container-fluid">
      <p>&copy; @DateTime.Today.Year Created by Md Thuaha</p>
    </footer>
    @RenderSection("scripts", false)
</body>
</html>

Mvc5_Project/Views/Shared/_Success.cshtml
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>Success!</strong> New Seller Add.
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>